WebBlog/Areas/Administrator/Controllers/BoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebBlog.Areas.Administrator.Controllers
{
    [Authorize]
    [Area("Administrator")]
    public class BoardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebBlog/Areas/Administrator/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using ReflectionIT.Mvc.Paging;
using WebBlog.Database.Data;
using WebBlog.Database.Models;
using WebBlog.Services.IServices;
using WebBlog.Common;

namespace WebBlog.Areas.Administrator.Controllers
{
    [Authorize]
    [Area("Administrator")]
    public class CommentsController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ICommentService _commentServicce;
        private readonly UserManager<ApplicationUser> _userManager;

        public CommentsController(ICommentService commentServicce, IConfiguration configuration, UserManager<ApplicationUser> userManager)
        {
            _commentServicce = commentServicce;
            _configuration = configuration;
            _userManager = userManager;
        }

        // GET: Administrator/Comments
        public async Task<IActionResult> Index(int page = 1, string sortExpression = "CreatedBy")
        {
            var qry = _commentServicce.GetAllOrderByCreatedBy();
            var model = await PagingList.CreateAsync(qry, Constants.PageSizeAdmin, page, sortExpression, "CreatedBy");
            ViewBag.ClientUrl = _configuration["ClientUIUrl"].ToString();
            return View(model);
        }

        // GET: Administrator/Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _commentServicce.GetByIdAsync(id.Value);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Administrator/Comments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Administrator/Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
     [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CommentId,Type,ParentId,CreatedDate,CreatedBy,IsDeleted,DeletedDate,DeletedBy,UpdatedDate,UpdatedBy,IsApproved,Content,Ext,ArticleId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                await _commentServicce.CreateAsync(comment);
                return RedirectToAction(nameof(Index));
            }
            return View(comment);
        }

        // GET: Administrator/Comments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _commentServicce.GetByIdAsync(id.Value);
            if (comment == null)
            {
                return NotFound();
            }
            return View(comment);
        }

        // POST: Administrator/Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
     [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CommentId,Type,ParentId,CreatedDate,CreatedBy,IsDeleted,DeletedDate,DeletedBy,UpdatedDate,UpdatedBy,IsApproved,Content,Ext,ArticleId")] Comment comment)
        {
            if (id != comment.CommentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.GetUserAsync(User);
                    if (user == null)
                    {
                        throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
                    }

                    comment.UpdatedBy = user.Email;
                    comment.UpdatedDate = DateTime.Now;

                    await _commentServicce.UpdateAsync(comment);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.CommentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(comment);
        }

        // GET: Administrator/Comments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _commentServicce.GetByIdAsync(id.Value);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Administrator/Comments/Delete/5
        [HttpPost, ActionName("Delete")]
     [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comment = await _commentServicce.GetByIdAsync(id);

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            comment.DeletedBy = user.Email;
            comment.DeletedDate = DateTime.Now;
            comment.IsDeleted = true;
            await _commentServicce.UpdateAsync(comment);

            return RedirectToAction(nameof(Index));
        }

        private bool CommentExists(int id)
        {
            return _commentServicce.CommentExists(id);
        }
    }
}

WebBlog/Areas/Administrator/Controllers/HelpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace WebBlog.Areas.Administrator.Controllers
{
    [Authorize]
    [Area("Administrator")]
    public class HelpController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebBlog/Areas/Client/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebBlog.Database.Data;
using WebBlog.Database.Models;

namespace WebBlog.Areas.Client.Controllers
{
    [Produces("application/json")]
    [Route("api/Articles")]
    public class ArticlesController : Controller
    {
        private readonly WebBlogDbContext _context;

        public ArticlesController(WebBlogDbContext context)
        {
            _context = context;
        }

        // GET: api/Articles
        [HttpGet]
        public IEnumerable<Article> GetArticles()
        {
            return _context.Articles;
        }

        // GET: api/Articles/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetArticle([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var article = await _context.Articles.SingleOrDefaultAsync(m => m.ArticleId == id);

            if (article == null)
            {
                return NotFound();
            }

            return Ok(article);
        }

        // PUT: api/Articles/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutArticle([FromRoute] int id, [FromBody] Article article)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != article.ArticleId)
            {
                return BadRequest();
            }

            _context.Entry(article).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ArticleExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Articles
        [HttpPost]
        public async Task<IActionResult> PostArticle([FromBody] Article article)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _context.Articles.Add(article);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetArticle", new { id = article.ArticleId }, article);
        }

        // DELETE: api/Articles/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteArticle([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var article = await _context.Articles.SingleOrDefaultAsync(m => m.ArticleId == id);
            if (article == null)
            {
                return NotFound();
            }

            _context.Articles.Remove(article);
            await _context.SaveChangesAsync();

            return Ok(article);
        }

        private bool ArticleExists(int id)
        {
            return _context.Articles.Any(e => e.ArticleId == id);
        }
    }
}

WebBlog/Areas/Administrator/Views/Shared/_Admin.WebBlog.cshtml
<ul>
    <li class="active_home"><a asp-area="Administrator" asp-controller="Board" asp-action="Index"><i class="icon-home"></i>WebBlogBoard</a></li>
    <li class="active_category rightMenu">
        <span><i class="icon-business-card"></i>Danh mục</span>
        <ul class="ulRightMenu" style="display: none;">
            <li><a asp-area="Administrator" asp-controller="Categories" asp-action="Index"><i class="icol-page-white-stack"></i><span class="admin-text-menu category-all">Tất cả danh mục</span></a></li>
            <li><a asp-area="Administrator" asp-controller="Categories" asp-action="Create"><i class="icol-pencil"></i><span class="admin-text-menu category-insert">Thêm danh mục mới</span></a></li>
        </ul>
    </li>
    <li class="active_article rightMenu">
        <span><i class="icon-file"></i>Bài viết</span>
        <ul class="ulRightMenu" style="display: none;">
            <li><a asp-area="Administrator" asp-controller="Articles" asp-action="Index"><i class="icol-page-white-stack"></i><span class="admin-text-menu article-all">Tất cả bài viết</span></a></li>
            <li><a asp-area="Administrator" asp-controller="Articles" asp-action="Create"><i class="icol-pencil"></i><span class="admin-text-menu article-insert">Thêm bài viết mới</span></a></li>
            <li><a asp-area="Administrator" asp-controller="Articles" asp-action="Recycle"><i class="icol-bin-closed"></i><span class="admin-text-menu article-recycle">Thùng rác</span></a></li>
        </ul>
    </li>
    <li class="active_comment rightMenu">
        <span><i class="icon-comment"></i>Bình Luận</span>
        <ul class="ulRightMenu" style="display: none;">
            <li><a asp-area="Administrator" asp-controller="Comments" asp-action="Index"><i class="icol-page-white-stack"></i><span class="admin-text-menu comment-all">Tất cả bình luận</span></a></li>
            <li><a asp-area="Administrator" asp-controller="Comments" asp-action="Create"><i class="icol-pencil"></i><span class="admin-text-menu comment-insert">Thêm bình luận mới</span></a></li>
            <li><a asp-area="Administrator" asp-controller="Comments" asp-action="Recycle"><i class="icol-bin-closed"></i><span class="admin-text-menu comment-recycle">Thùng rác</span></a></li>
        </ul>
    </li>
    <li class="active_help"><a asp-area="Administrator" asp-controller="Help" asp-action="Index"><i class="icon-question-sign"></i>Help</a></li>
</ul>

WebBlog/Areas/Administrator/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using WebBlog.Database.Models
@using WebBlog.Views.Manage

@inject SignInManager<WebBlog.Database.Models.ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@

    <link href="~/css/fonts/style.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="~/css/screen.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="~/css/icons/icol16.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" media="screen" />

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/tiny_mce/tiny_mce.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <script type="text/javascript">
        tinyMCE.init({
            // General options
            mode: "exact",
            theme: "advanced",
            elements: 'richText, richText1, richText2, richText3',
            plugins: "autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,netadvimage",

            // Theme options
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,netadvimage,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            plugin_preview_width: "100%",
            width: 800,

            // Skin options
            skin: "o2k7",
            skin_variant: "silver",

            // Example content CSS (should be your site CSS)
            // content_css: "css/example.css",

            // Drop lists for link/image/media/template dialogs
            template_external_list_url: "js/template_list.js",
            external_link_list_url: "js/link_list.js",
            external_image_list_url: "js/image_list.js",
            media_external_list_url: "js/media_list.js",

            // Replace values for the template plugin
            template_replace_values: {
                username: "Some User",
                staffid: "991234"
            }
        });

        $(document).ready(function () {
            $("#multiSelectCheckbox").click(function () {
                var multiSelect = document.getElementById("multiSelectCheckbox");
                var multiDelete = document.getElementsByName("multiDelete");
                for (var i = 0; i < multiDelete.length; i++) {
                    multiDelete[i].checked = multiSelect.checked;
                }
            });
        });
    </script>
</head>
<body>
    <!-- Header -->
    <div id="mws-header" class="clearfix">
        <div id="mws-logo-container">
            <div id="mws-logo-wrap">
            </div>
        </div>
        <div id="mws-user-tools" class="clearfix">
            <div id="mws-home">
                <a href="/Home" target="_blank"><i class="icon-home"></i>Home</a>
            </div>
            <div id="mws-language">
                <a>
                    <i class="icon-flag"></i>
                </a>
            </div>
            <div id="mws-user-message" class="mws-dropdown-menu">
                <a href="#" data-toggle="dropdown" class="mws-dropdown-trigger">
                    <i class="icon-envelope">
                    </i>
                </a><span class="mws-dropdown-notif">2</span>
                <div class="mws-dropdown-box">
                    <div class="mws-dropdown-content">
                        <ul class="mws-messages">
                            <li class="unread">
                                <a href="#">
                                    <span class="sender">Tài Hoàng</span> <span class="message">

                                    </span><span class="time">
                                        30-04-2018
                                    </span>
                                </a>
                            </li>
                        </ul>

                        <div class="mws-dropdown-viewall">
                            <a href="#">Vào hộp thư</a>
                        </div>
                    </div>
                </div>
            </div>
            <div id="mws-user-info" class="mws-inset">
                <div id="mws-user-photo">
                    <img src="~/css/core/admin_user.png" alt="User Photo" />
                </div>
                <div id="mws-user-functions">
                    <div id="mws-username">
                        Welcome @UserManager.GetUserName(User)!
                    </div>
                    <ul>
                        <li><a asp-area="" asp-controller="Manage" asp-action="Index">Profile</a></li>
                        <li><a asp-area="" asp-controller="Manage" asp-action="ChangePassword">Password</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="mws-wrapper">
        <div id="mws-sidebar-stitch">
        </div>
        <div id="mws-sidebar-bg">
        </div>
        <div id="mws-sidebar">
            <div id="mws-searchbox" class="mws-inset">
                <form action="">
                    <input type="text" class="mws-search-input" placeholder="Search..." />
                    <button type="submit" class="mws-search-submit">
                        <i class="icon-search"></i>
                    </button>
                </form>
            </div>
            <div id="mws-navigation">
                @{Html.RenderPartial("_Admin.WebBlog.cshtml");}
            </div>
        </div>
        <div id="mws-container" class="clearfix">
            <div class="container">
                @RenderBody()
            </div>
            <div id="mws-footer">
                Copyright &copy; 2018 by WebBlog. All rights reserved.
            </div>
        </div>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>